apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  labels:
    app: my-pod-1
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx:latest
    #- name: busybox
    #  image: busybox:latest
